name: solar system workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs-version: [18, 19, 20]
        operating-system: [ubuntu-latest, macos-latest]
        exclude:
          - nodejs-version: 18
            operating-system: macos-latest

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.nodejs-version }}
      - name: Install dependencies npm
        run: |
          npm install

      # - name: Run unit tests
      #   run: |
      #     npm test

      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: Mocha Test Results
          path: test-results.xml
          overwrite: true
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies npm
        run: |
          npm install

      - name: Run code coverage
        run: |
          npm run coverage

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report
          path: coverage/cobertura-coverage.xml
        